export enum ProjectsActionType {
  GETALL_STARTED = "GETALL_STARTED",
  GETALL_SUCCESS = "GETALL_SUCCESS",
  GETALL_FAILURE = "GETALL_FAILURE",

  SET_PROJECT_TAB = "SET_PROJECT_TAB",
  REMOVE_PROJECT_TAB = "REMOVE_PROJECT_TAB",

  SET_PROJECT_SELECTED = "SET_PROJECT_SELECTED"
}